// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtfIcCfiFHTGLwqut5j6dVxfid32s2mgM',
    appId: '1:565886927863:web:9b17983fc0d5c97ef3a4f2',
    messagingSenderId: '565886927863',
    projectId: 'uang-92d18',
    authDomain: 'uang-92d18.firebaseapp.com',
    storageBucket: 'uang-92d18.firebasestorage.app',
    measurementId: 'G-LRZM7EWRMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwwCI8iIfHeE4jOI-8z2to_ajUq10fPg',
    appId: '1:565886927863:android:d36f337f18db1722f3a4f2',
    messagingSenderId: '565886927863',
    projectId: 'uang-92d18',
    storageBucket: 'uang-92d18.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtfIcCfiFHTGLwqut5j6dVxfid32s2mgM',
    appId: '1:565886927863:web:af51ff321ad8f2fcf3a4f2',
    messagingSenderId: '565886927863',
    projectId: 'uang-92d18',
    authDomain: 'uang-92d18.firebaseapp.com',
    storageBucket: 'uang-92d18.firebasestorage.app',
    measurementId: 'G-XNM32NK96X',
  );
}
